### ISSUE TITLE
Address bugs.

### ISSUE THREAD

**Issue by wheremyfoodat** [htmlcsjs/gb-emu#1]
Opcode 0x2, LD (BC), A does not do `regC = regA;` as the emulator's code implies.
Instead, it stores A in the address pointed to by the BC register.

For example if B = 0xDD, C = 0xAA and A = 0x30, it would write 0x30 to address 0xDDAA

Also `inc BC` is wrong too. Imagine it in pseudocode as something like
```cpp
uint16_t BC = (B << 8) | C;
BC++;

C = BC & 0xFF;
B = BC >> 8;
```
(though please abstract it in a nice way)

Also for `inc b`
Your code sets the Z and H flags if the result is 0 or if there was a half carry respectively. HOWEVER, it should also unset those flags if these conditions are false.
So if res != 0, the zero flag should be turned off, and if there was no half carry, the half carry flag should be turned off

**Comment by htmlcsjs** [comment]
Oh thank you, I’ll fix that later

**Comment by wheremyfoodat** [comment]
np
